name:                cobbal-blog
version:             0.1.0.0
github:              "cobbal/cobbal-blog"
license:             BSD3
author:              "Andrew Cobb"
maintainer:          "andrew.cobb@gmail.com"
copyright:           "2025 Andrew Cobb"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            cobbal's blog
category:            Slick-Site

description: cobbal's blog

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - time
